version: "2.2"

services:
  code-server:
    image: kodelib/code-server:3.8.0-r2-alpine
    command:
      - --host=0.0.0.0
    environment:
      PASSWORD: "1234567890"
  
  sidecar:
    image: kodelib/code-server-sidecar:${VERSION}
    build:
      context: .
    ports:
      - 8080:80
    environment:
      BASE_PATH: /code/
      PROXY_URL: http://code-server:8080/
