name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Quality
        env:
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: |
          brew install hadolint
          find . -type f -name "Dockerfile*" -print0 | xargs -0 -n1 hadolint

      - name: Build images
        run: |
          docker-compose build